### ISSUE TITLE
Campo neighborhoods.slug como varchar(40) está muito curto

### ISSUE THREAD

**Issue by fredsvanelli** [mixdinternet/cities#1]
Ao executar o seeder de bairros, recebi um erro dizendo que houve uma tentativa de cadastrar um bairro com slug que excede os 40 caracteres permitidos. Aumentei para varchar(255) e não tive mais problemas.

Aproveito para dizer que está de parabéns, excelente projeto, muito útil.

**Comment by jleonardolemos** [comment]
Que bom que gostou @fredsvanelli , já corrigimos o slug e o name.
